name: MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download deps
        id: downloadDeps
        working-directory: ${{github.workspace}}
        run: |
          wget https://download.qt.io/official_releases/qt/6.2/6.2.4/single/qt-everywhere-src-6.2.4.tar.xz -q
          tar -xJf qt-everywhere-src-6.2.4.tar.xz
            
      - name: Setup Ninja
        run: |
          brew install ninja

      - name: Make dir
        working-directory: ${{github.workspace}}
        run: |
          mkdir out
          mkdir build

      - name: Configure qt
        working-directory: ${{github.workspace}}
        run: |
          export PATH="/usr/local/bin:$PATH"
          cd qt-everywhere-src-6.2.4
          ./configure -prefix ${{github.workspace}}/out/qt -opensource -confirm-license -release -static -no-pch -no-dbus -no-feature-gssapi -gui -nomake examples -nomake tests -skip qtconnectivity -skip qtdeclarative -skip qtlocation -skip qtmultimedia -skip qtquick1 -skip qtquickcontrols -skip qtsensors -skip qtdoc -skip qtlottie -skip qtmqtt -skip qtopcua -skip qtquicktimeline -skip qtquick3d -skip qtscxml -skip qtvirtualkeyboard -skip qtwebengine -skip qtwebview -skip qt3d -skip qtserialbus --webp=qt --tiff=qt -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

      - name: Build qt
        working-directory: ${{github.workspace}}
        run: |
          cd qt-everywhere-src-6.2.4
          cmake --build . --parallel
          ninja install
          cd ${{github.workspace}}
          rm -rf qt-everywhere-src-6.2.4

      - name: Pack files
        working-directory: ${{github.workspace}}/out
        run: |
          tar -cJf qt.tar.xz qt

      - uses: actions/upload-artifact@v2
        with:
          path: ${{github.workspace}}/out/*.tar.xz

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "out/*.tar.xz"
          overwrite: true
          tags: true
          draft: false
